spring:

  #H2 console
  h2.console:
    enabled: false

  #Database
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1

  #Redis
  redis:
    host: localhost
    port: 6385

  #RabbitMq
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5685

  #Mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: bookstore.application.akej@gmail.com
    password: whhzaeshzetyxnka
    properties.mail.smtp:
      auth: true
      starttls.enable: true

