version: '3'
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: bookstore_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3308:3306"
    volumes:
      - bookstore-mysql:/var/lib/mysql
    container_name: mysql

  redis:
    image: redis:7.0
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - bookstore-redis:/data
    container_name: redis

  rabbitmq:
    image: rabbitmq:3.12.0-rc.2-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - bookstore-rabbitmq:/var/lib/rabbitmq
    container_name: rabbitmq

  jenkins:
    image: jenkins/jenkins:latest-jdk17
    restart: always
    ports:
      - "8090:8080"
    volumes:
      - bookstore-jenkins:/var/jenkins_home
    container_name: jenkins

  app:
    image: bookstore-app:1.1
    ports:
      - "8082:8080"
    environment:
      REDIS_URL: redis://redis:6381/0
      MYSQL_HOST: mysql://mysql:3308/bookstore_db
    depends_on:
      - mysql
      - redis
      - rabbitmq
      - jenkins
    container_name: app

networks:
  bookstore-network:

volumes:
  bookstore-mysql:
  bookstore-redis:
  bookstore-rabbitmq:
  bookstore-jenkins:

#docker-compose up