spring:
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:file:/Users/Aleks/Desktop/bookstore/bookstore/db/bookstore-db

  liquibase:
    change-log: classpath:/dbchangelog.xml

server:
  error:
    whitelabel:
      enabled: false



